name: C/C++ CI

on:
  push:
    branches:
    - master
    - CItest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create build file
        run: |
          mkdir build 
          cd build
      - name: Run cmake make
        run: |
          cmake
          make 
          cd ..
      - name: Run unitTests
        run: |
          cd unitTests
          gcc test.c -o test -lcunit
          ./test
        
