name: C/C++ CI

on:
  pull_request:
  push:
    branches:
    - master
    - CItest

jobs:
  build:

    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download dependecies
        run: sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
      - name: Run unitTests
        run: |
          gcc test.c -o test -lcunit
          ./test
        
